import type React from "react";

export interface TranslationsMap {
	[locale: string]: {
		[key: string]: string;
	};
}

export interface LocaleInfo {
	nativeName: string; // "Español", "简体中文"
	dir?: "rtl"; // Only for RTL locales
	currencyCode?: string; // ISO 4217: "USD", "EUR", "GBP", etc.
}

export interface LocalesMap {
	[localeCode: string]: LocaleInfo;
}

export interface VocoderContextValue {
	availableLocales: string[];
	getDisplayName: (targetLocale: string, viewingLocale?: string) => string;
	/** True when initial translations are ready for render */
	isReady: boolean;
	locale: string;
	/** Text direction for the current locale. 'rtl' for Arabic, Hebrew, etc. 'ltr' for all others. */
	dir: "ltr" | "rtl";
	locales?: LocalesMap;
	setLocale: (locale: string) => Promise<void>;
	t: (text: string) => string;
	hasTranslation: (text: string) => boolean;
}

export interface VocoderProviderServerProps {
	children: React.ReactNode;
	locale?: string;
	translations?: Record<string, string>;
}

export interface VocoderProviderProps {
	/** React children */
	children: React.ReactNode;
	/**
	 * Cookie string for server-side rendering (optional)
	 * Pass cookies from request headers to enable SSR locale detection
	 * @example Next.js App Router: cookies().toString()
	 * @example Next.js Pages: context.req.headers.cookie
	 */
	cookies?: string;
	/**
	 * Automatically apply `dir` and `lang` attributes to `document.documentElement`
	 * when the locale changes. Enables RTL layout for Arabic, Hebrew, etc. via CSS
	 * frameworks that respond to `[dir="rtl"]` (Tailwind `rtl:` variants, etc.).
	 *
	 * On by default — set to false only if you manage document direction yourself.
	 * @default true
	 */
	applyDir?: boolean;
}

export interface TProps {
	/** Optional stable translation key. When provided, used as lookup key instead of message text. */
	id?: string;
	/** Source text / fallback content */
	children?: React.ReactNode;
	/**
	 * Message template for translation. Used as the translation lookup key.
	 * Supports ICU MessageFormat syntax and named component placeholders.
	 * @example Simple interpolation
	 * ```tsx
	 * <T message="Hello {name}!" values={{ name }} />
	 * ```
	 * @example Rich text
	 * ```tsx
	 * <T message="Click <link>here</link>" components={{ link: <a href="/help" /> }} />
	 * ```
	 */
	message?: string;
	/** @deprecated Use `message` instead */
	msg?: string;
	/** Values for variable interpolation. Merged with any additional spread props. */
	values?: Record<string, any>;
	/**
	 * The value that drives plural or select selection.
	 * - Plural mode (number): matched against Intl.PluralRules for the active locale
	 * - Select mode (string): matched against _case props
	 */
	value?: string | number;
	/** Optional context string for disambiguation (same text, different meaning) */
	context?: string;
	/** Optional formality level */
	formality?: "formal" | "informal" | "auto";
	/** Component placeholders for rich-text messages, keyed by tag name */
	components?: Record<string, React.ReactElement>;
	/**
	 * CLDR plural categories — triggers plural mode when present alongside `value`.
	 * Use # as placeholder for the formatted number.
	 */
	one?: string;
	two?: string;
	few?: string;
	many?: string;
	other?: string;
	/**
	 * Dynamic props for plural/select mode only:
	 * - _0, _1, _2 — exact numeric matches in plural mode (ICU =0, =1, =2)
	 * - _male, _female, _nonbinary, etc. — select cases (requires string value prop)
	 *
	 * For interpolation variables use the `values` prop instead.
	 * Spread props are NOT used as interpolation values to avoid name collisions
	 * with reserved props (one, other, value, message, etc.).
	 */
	[key: string]: any;
}

export interface LocaleSelectorProps {
	/** Position of the locale selector on the screen */
	position?:
		| "top-left"
		| "top-right"
		| "bottom-left"
		| "bottom-right"
		| "tl"
		| "tr"
		| "bl"
		| "br";
	/**
	 * Color scheme mode for the button and logo.
	 * - 'auto': follows system/CSS `prefers-color-scheme` (default)
	 * - 'light': force light theme (white bg, dark logo)
	 * - 'dark': force dark theme (dark bg, light logo)
	 * @default 'auto'
	 */
	mode?: "light" | "dark" | "auto";
	/** Background color of the button and dropdown. Overrides auto mode. */
	background?: string;
	/** Text and icon color. Overrides auto mode. */
	color?: string;
	/** Additional CSS class name */
	className?: string;
	/** Size of the logo icon in pixels */
	iconSize?: number;
	/**
	 * Locale metadata map (auto-generated by CLI)
	 * Structure: { [localeCode]: { nativeName, dir? } }
	 * - nativeName: Name in the target locale's own language (e.g., "Español", "简体中文")
	 * - dir: Optional 'rtl' for right-to-left locales
	 *
	 * Example:
	 * {
	 *   'en': { nativeName: 'English' },
	 *   'es': { nativeName: 'Español' },
	 *   'ar': { nativeName: 'العربية', dir: 'rtl' }
	 * }
	 *
	 * Translated names are generated at runtime using Intl.DisplayNames
	 * Display format: `${getDisplayName(code)} (${locales[code].nativeName})`
	 */
	locales?: LocalesMap;
	/**
	 * How to sort the locale dropdown items
	 * - 'native': Sort by native names (e.g., "Deutsch", "Español") - consistent across all locales (default)
	 * - 'source': Sort by English names - consistent across all locales
	 * - 'translated': Sort by translated names in the current viewing locale - order changes per locale
	 *
	 * @default 'native'
	 */
	sortBy?: "source" | "native" | "translated";
}
