import React from 'react';

// Translation data structure
export interface TranslationsMap {
  [locale: string]: {
    [key: string]: string;
  };
}

// Locale metadata structure (auto-generated by CLI)
// O(N) flat structure - use Intl.DisplayNames at runtime for translated names
export interface LocaleInfo {
  nativeName: string;     // "Español", "简体中文"
  dir?: 'rtl';            // Only for RTL locales
  currencyCode?: string;  // ISO 4217: "USD", "EUR", "GBP", etc.
}

export interface LocalesMap {
  [localeCode: string]: LocaleInfo;
}

// Context value for the Vocoder provider
export interface VocoderContextValue {
  availableLocales: string[];
  getDisplayName: (targetLocale: string, viewingLocale?: string) => string;
  locale: string;
  locales?: LocalesMap;
  setLocale: (locale: string) => void;
  t: (text: string) => string;
}

// Props for the VocoderProvider component
export interface VocoderProviderProps {
  /** React children */
  children: React.ReactNode;
  /** Default locale to use */
  defaultLocale?: string;
  /** Static translations object (recommended for production) */
  translations?: TranslationsMap;
  /** Locale metadata with names (auto-generated by CLI, optional) */
  locales?: LocalesMap;
  /**
   * Cookie string for server-side rendering (optional)
   * Pass cookies from request headers to enable SSR locale detection
   * @example Next.js App Router: cookies().toString()
   * @example Next.js Pages: context.req.headers.cookie
   */
  cookies?: string;
}

// Props for the VocoderProviderServer component (SSR)
export interface VocoderProviderServerProps {
  /** Current locale */
  locale: string;
  /** Translations for the current locale */
  translations: Record<string, string>;
  /** React children */
  children: React.ReactNode;
}

// Props for the T component
export interface TProps {
  /** Source text to translate (also used as the translation key) */
  children?: React.ReactNode;
  /**
   * Message string for translation (alternative to children)
   * Useful for ICU MessageFormat strings to avoid JSX escaping
   * If both msg and children are provided, msg takes precedence
   * @example
   * ```tsx
   * <T msg="{count, plural, one {# item} other {# items}}" count={5} />
   * ```
   */
  msg?: string;
  /** Optional context for disambiguation */
  context?: string;
  /** Optional formality level */
  formality?: 'formal' | 'informal' | 'auto';
  /**
   * Components for rich text interpolation (Phase 3)
   * Maps component names to React elements
   * @example
   * ```tsx
   * <T components={{ link: <a href="/help" /> }}>
   *   Click <link>here</link> for help
   * </T>
   * ```
   */
  components?: Record<string, React.ReactElement>;
  /** Additional props for variable interpolation (e.g., name="John", count={5}) */
  [key: string]: any;
}

// Props for the LocaleSelector component
export interface LocaleSelectorProps {
  /** Position of the locale selector on the screen */
  position?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'tl' | 'tr' | 'bl' | 'br';
  /** Background color of the button and dropdown */
  background?: string;
  /** Text color */
  color?: string;
  /** Additional CSS class name */
  className?: string;
  /** Size of the globe icon in pixels */
  iconSize?: number;
  /**
   * Locale metadata map (auto-generated by CLI)
   * Structure: { [localeCode]: { nativeName, dir? } }
   * - nativeName: Name in the target locale's own language (e.g., "Español", "简体中文")
   * - dir: Optional 'rtl' for right-to-left locales
   *
   * Example:
   * {
   *   'en': { nativeName: 'English' },
   *   'es': { nativeName: 'Español' },
   *   'ar': { nativeName: 'العربية', dir: 'rtl' }
   * }
   *
   * Translated names are generated at runtime using Intl.DisplayNames
   * Display format: `${getDisplayName(code)} (${locales[code].nativeName})`
   */
  locales?: LocalesMap;
  /**
   * How to sort the locale dropdown items
   * - 'source': Sort by English names (using en locale) - consistent across all locales (default)
   * - 'native': Sort by native names - consistent across all locales
   * - 'translated': Sort by translated names in the current viewing locale - order changes per locale
   *
   * @default 'source'
   */
  sortBy?: 'source' | 'native' | 'translated';
}
