import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, describe, expect, it, vi } from "vitest";
import { writeLocaleFileTree } from "../commands/pull.js";

// ── writeLocaleFileTree ───────────────────────────────────────────────────────

describe("writeLocaleFileTree", () => {
	let tmpDir: string;

	afterEach(() => {
		rmSync(tmpDir, { recursive: true, force: true });
	});

	function makeTmpDir(): string {
		const dir = join(tmpdir(), `pull-test-${Date.now()}`);
		mkdirSync(dir, { recursive: true });
		tmpDir = dir;
		return dir;
	}

	it("writes each file from the tree to disk", () => {
		const root = makeTmpDir();
		const tree: Record<string, string> = {
			"locales/manifest.json": '{"version":1}\n',
			"locales/en.json": '{"1abc":"Hello"}\n',
			"locales/es.json": '{"1abc":"Hola"}\n',
		};

		writeLocaleFileTree(tree, root);

		for (const [relativePath, content] of Object.entries(tree)) {
			const filePath = join(root, relativePath);
			expect(readFileSync(filePath, "utf-8")).toBe(content);
		}
	});

	it("creates nested directories recursively", () => {
		const root = makeTmpDir();
		writeLocaleFileTree({ "locales/deep/nested/en.json": '{"k":"v"}\n' }, root);
		expect(readFileSync(join(root, "locales/deep/nested/en.json"), "utf-8")).toBe('{"k":"v"}\n');
	});

	it("overwrites existing files", () => {
		const root = makeTmpDir();
		mkdirSync(join(root, "locales"), { recursive: true });
		const filePath = join(root, "locales/en.json");
		writeFileSync(filePath, '{"old":"value"}\n', "utf-8");

		writeLocaleFileTree({ "locales/en.json": '{"new":"value"}\n' }, root);

		expect(readFileSync(filePath, "utf-8")).toBe('{"new":"value"}\n');
	});

	it("writes multiple locale files and manifest", () => {
		const root = makeTmpDir();
		const tree: Record<string, string> = {
			"locales/manifest.json": '{"version":1,"sourceLocale":"en","targetLocales":["es","fr"]}\n',
			"locales/en.json": '{"key1":"Source text"}\n',
			"locales/es.json": '{"key1":"Texto fuente"}\n',
			"locales/fr.json": '{"key1":"Texte source"}\n',
		};

		writeLocaleFileTree(tree, root);

		const localesDir = join(root, "locales");
		const files = readdirSync(localesDir).sort();
		expect(files).toEqual(["en.json", "es.json", "fr.json", "manifest.json"]);
	});

	it("writes loader.js for non-TypeScript projects", () => {
		const root = makeTmpDir();
		const loaderJs =
			'// Auto-generated by Vocoder. Do not edit.\nexport async function loadLocale(locale) {\n  switch (locale) {\n    case "en": return import("./en.json").then((m) => m.default ?? m);\n    default: return {};\n  }\n}\n';

		writeLocaleFileTree({ "locales/loader.js": loaderJs }, root);

		expect(existsSync(join(root, "locales/loader.js"))).toBe(true);
		expect(existsSync(join(root, "locales/loader.ts"))).toBe(false);
		expect(existsSync(join(root, "locales/loader.d.ts"))).toBe(false);
		expect(readFileSync(join(root, "locales/loader.js"), "utf-8")).toBe(loaderJs);
	});

	it("writes loader.ts with type annotations for TypeScript projects", () => {
		const root = makeTmpDir();
		const loaderJs =
			'// Auto-generated by Vocoder. Do not edit.\nexport async function loadLocale(locale) {\n  switch (locale) {\n    case "en": return import("./en.json").then((m) => m.default ?? m);\n    default: return {};\n  }\n}\n';

		writeLocaleFileTree({ "locales/loader.js": loaderJs }, root, { isTypeScript: true });

		expect(existsSync(join(root, "locales/loader.js"))).toBe(false);
		expect(existsSync(join(root, "locales/loader.d.ts"))).toBe(false);
		expect(existsSync(join(root, "locales/loader.ts"))).toBe(true);
		const content = readFileSync(join(root, "locales/loader.ts"), "utf-8");
		expect(content).toContain("async function loadLocale(locale: string): Promise<Record<string, string>>");
	});

	// ── what the GitHub Action stages ────────────────────────────────────────
	//
	// The Action no longer re-derives paths from the server's tree; it stages
	// `written` and `removed` verbatim. If these lists describe anything other
	// than the files on disk, the commit is wrong in the customer's repository.

	it("reports the paths it wrote, matching the tree keys for a plain JS project", () => {
		const root = makeTmpDir();
		const outcome = writeLocaleFileTree(
			{ "locales/en.json": '{"k":"v"}\n', "locales/es.json": '{"k":"w"}\n' },
			root,
		);
		expect(outcome.written.sort()).toEqual(["locales/en.json", "locales/es.json"]);
		expect(outcome.removed).toEqual([]);
	});

	it("reports loader.ts — not the loader.js key the server sent — for a TypeScript project", () => {
		const root = makeTmpDir();
		const outcome = writeLocaleFileTree(
			{ "locales/loader.js": "export async function loadLocale(locale) {}\n" },
			root,
			{ isTypeScript: true },
		);
		expect(outcome.written).toEqual(["locales/loader.ts"]);
		expect(outcome.written).not.toContain("locales/loader.js");
	});

	it("reports a superseded loader.js as removed so the Action can stage the deletion", () => {
		const root = makeTmpDir();
		mkdirSync(join(root, "locales"), { recursive: true });
		writeFileSync(join(root, "locales/loader.js"), "old js\n", "utf-8");
		writeFileSync(join(root, "locales/loader.d.ts"), "old dts\n", "utf-8");

		const outcome = writeLocaleFileTree(
			{ "locales/loader.js": "export async function loadLocale(locale) {}\n" },
			root,
			{ isTypeScript: true },
		);

		expect(outcome.removed.sort()).toEqual(["locales/loader.d.ts", "locales/loader.js"]);
		expect(outcome.written).toEqual(["locales/loader.ts"]);
	});

	it("reports nothing removed when there was no stale loader to delete", () => {
		const root = makeTmpDir();
		const outcome = writeLocaleFileTree(
			{ "locales/loader.js": "export async function loadLocale(locale) {}\n" },
			root,
			{ isTypeScript: true },
		);
		expect(outcome.removed).toEqual([]);
	});

	// ── path containment ─────────────────────────────────────────────────────
	//
	// The tree is server-supplied and is applied inside a checkout where the
	// Action holds `contents: write`. A key that escapes the root would be
	// written and then committed.

	it("refuses a key that escapes the repository root, writing nothing", () => {
		const root = makeTmpDir();
		expect(() =>
			writeLocaleFileTree(
				{
					"locales/en.json": '{"k":"v"}\n',
					"../../.github/workflows/deploy.yml": "on: push\n",
				},
				root,
			),
		).toThrow(/outside the repository/);
		// The whole tree is validated before anything is written, so the
		// legitimate sibling key must not have landed either.
		expect(existsSync(join(root, "locales/en.json"))).toBe(false);
	});

	it("refuses an absolute key", () => {
		const root = makeTmpDir();
		expect(() =>
			writeLocaleFileTree({ "/etc/passwd": "root\n" }, root),
		).toThrow(/outside the repository/);
	});

	it("refuses a key that escapes via a traversal segment in the middle", () => {
		const root = makeTmpDir();
		expect(() =>
			writeLocaleFileTree({ "locales/../../escaped.json": "{}\n" }, root),
		).toThrow(/outside the repository/);
	});

	it("allows a traversal segment that stays inside the root, and reports the resolved path", () => {
		const root = makeTmpDir();
		const outcome = writeLocaleFileTree({ "app/../locales/en.json": '{"k":"v"}\n' }, root);
		expect(readFileSync(join(root, "locales/en.json"), "utf-8")).toBe('{"k":"v"}\n');
		// `git add app/../locales/en.json` would be asked to walk an "app/"
		// directory that need not exist — the reported path is the real one.
		expect(outcome.written).toEqual(["locales/en.json"]);
	});

	it("cleans up stale loader.js and loader.d.ts when writing loader.ts", () => {
		const root = makeTmpDir();
		mkdirSync(join(root, "locales"), { recursive: true });
		writeFileSync(join(root, "locales/loader.js"), "old js\n", "utf-8");
		writeFileSync(join(root, "locales/loader.d.ts"), "old dts\n", "utf-8");

		const loaderJs =
			'// Auto-generated by Vocoder. Do not edit.\nexport async function loadLocale(locale) {\n  default: return {};\n}\n';
		writeLocaleFileTree({ "locales/loader.js": loaderJs }, root, { isTypeScript: true });

		expect(existsSync(join(root, "locales/loader.js"))).toBe(false);
		expect(existsSync(join(root, "locales/loader.d.ts"))).toBe(false);
		expect(existsSync(join(root, "locales/loader.ts"))).toBe(true);
	});
});

// ── VocoderAPI.getLocaleFiles (mocked fetch) ──────────────────────────────────

describe("VocoderAPI.getLocaleFiles", () => {
	const originalFetch = globalThis.fetch;

	afterEach(() => {
		vi.restoreAllMocks();
		globalThis.fetch = originalFetch;
	});

	it("returns FOUND with apps array on success", async () => {
		const localeFileTree = {
			"locales/manifest.json": '{"version":1}\n',
			"locales/en.json": '{"k":"v"}\n',
		};
		globalThis.fetch = vi.fn().mockResolvedValue({
			ok: true,
			status: 200,
			text: async () =>
				JSON.stringify({
					status: "FOUND",
					branch: "main",
					apps: [{ appDir: "", localeFileTree }],
				}),
		} as Response);

		const { VocoderAPI } = await import("../utils/api.js");
		const api = new VocoderAPI({
			apiKey: "vcp_aB3xY9Zk_testrandombytes123456",
			apiUrl: "https://vocoder.app",
		});
		const result = await api.getLocaleFiles({ branch: "main" });

		expect(result.status).toBe("FOUND");
		expect(result.apps).toHaveLength(1);
		expect(result.apps[0].localeFileTree).toEqual(localeFileTree);
	});

	it("returns NOT_FOUND when no translations exist", async () => {
		globalThis.fetch = vi.fn().mockResolvedValue({
			ok: true,
			status: 200,
			text: async () =>
				JSON.stringify({ status: "NOT_FOUND", branch: "main", apps: [] }),
		} as Response);

		const { VocoderAPI } = await import("../utils/api.js");
		const api = new VocoderAPI({
			apiKey: "vcp_aB3xY9Zk_testrandombytes123456",
			apiUrl: "https://vocoder.app",
		});
		const result = await api.getLocaleFiles({ branch: "main" });

		expect(result.status).toBe("NOT_FOUND");
		expect(result.apps).toHaveLength(0);
	});

	it("sends only branch in query params", async () => {
		const mockFetch = vi.fn().mockResolvedValue({
			ok: true,
			status: 200,
			text: async () =>
				JSON.stringify({ status: "NOT_FOUND", branch: "feat/x", apps: [] }),
		} as Response);
		globalThis.fetch = mockFetch;

		const { VocoderAPI } = await import("../utils/api.js");
		const api = new VocoderAPI({
			apiKey: "vcp_aB3xY9Zk_testrandombytes123456",
			apiUrl: "https://vocoder.app",
		});
		await api.getLocaleFiles({ branch: "feat/x" });

		const [url] = mockFetch.mock.calls[0] as [string];
		expect(url).toContain("/api/project/translations/pull");
		expect(url).toContain("branch=feat%2Fx");
		expect(url).not.toContain("appDir");
	});
});
